### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SanQianQVQ**
Added Cloudflare info and use of bright red ❌ for readability.

    None

### CODE REVIEW

**Comment by longjuan** [comment]
麻烦测试一下兼容访问风格，不知道Path Style还能不能用。
https://developers.cloudflare.com/r2/platform/changelog/#2022-05-16
> Add support for S3 virtual-hosted style paths, such as <BUCKET>.<ACCOUNT_ID>.r2.cloudflarestorage.com instead of path-based routing (<ACCOUNT_ID>.r2.cloudflarestorage.com/<BUCKET>).

**Comment by SanQianQVQ** [comment]
@longjuan 文档中给出的 <ACCOUNT_ID>.r2.cloudflarestorage.com/< BUCKET> 可用。

**Comment by longjuan** [comment]
> @longjuan 文档中给出的 <ACCOUNT_ID>.r2.cloudflarestorage.com/< BUCKET> 可用。

是用的最新版1.3.0吗，Endpoint填`<ACCOUNT_ID>.r2.cloudflarestorage.com`然后选择Path Style

**Comment by SanQianQVQ** [comment]
> > @longjuan 文档中给出的 <ACCOUNT_ID>.r2.cloudflarestorage.com/< BUCKET> 可用。
> 
> 是用的最新版1.3.0吗，Endpoint填`<ACCOUNT_ID>.r2.cloudflarestorage.com`然后选择Path Style

1.3.0
Endpoint `<ACCOUNT_ID>.r2.cloudflarestorage.com` Path Style
Endpoint `<ACCOUNT_ID>.r2.cloudflarestorage.com` Virtual Hosted Style
均可以正常上传和删除

**Pull request merged**
